name: ASkyBlock
main: com.wasteofplastic.askyblock.ASkyBlock
version: 2.7.9
description: A SkyBlock Plugin
author: Tastybento
depend: [Vault]
softdepend: [WorldEdit]
load: startup
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Main player command
        aliases: [is, island, as]
        usage:  |
             /island help
    asadmin:
        description: Admin commands
        usage:  |
            /asadmin
    asc:
        description: Game challenges
        aliases: [c, challenge, aschallenge, challenges]
        usage:  |  
            /challenge
permissions:    
  askyblock.*:
    children:
      askyblock.island.*:
        children:
          askyblock.island.create:
            description: Let the player use the /island command
            default: true
          askyblock.island.info:
            description: Let the player check their island level
            default: true
          askyblock.island.topten:
            description: Let the player see the top ten list
            default: true
          askyblock.island.sethome:
            description: Let the player set their island teleport point
            default: true
          askyblock.island.challenges:
            description: Let the player use the /challenges command
            default: true
          askyblock.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          askyblock.island.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
          askyblock.island.minishop:
            description: Allows usage of the minishop
            default: true
          askyblock.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
          askyblock.island.biomes:
            description: Allows biome changing
            default: true
      askyblock.team.*:
        children:
          askyblock.team.create:
            description: Let a player invite other players to join a team
            default: true
          askyblock.team.kick:
            description: Let a player kick other players
            default: true
          askyblock.team.makeleader:
            description: Let a player make another player leader of the team
            default: true
          askyblock.team.join:
            description: Let a player join another player's team
            default: true
          askyblock.team.vip:
            description: Allows a bigger team size
            default: false
          askyblock.team.vip2:
            description: Allows a bigger team size
            default: false
      askyblock.coop:
        description: Allows player to use the coop command
        default: false
      askyblock.craft.*:
        children:
          askyblock.craft.enderchest:
            description: Allow crafting and use of enderchests in askyblock
            default: false
      askyblock.mod.*:
        children:
          askyblock.mod.topten:
            description: Let a moderator update the top ten list
            default: op
          askyblock.mod.info:
            description: Let a moderator see info on a player
            default: op
          askyblock.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          askyblock.mod.noburn:
            description: Gives mod immunity to acid
            default: false
          askyblock.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          askyblock.mod.tp:
            description: Allows teleport to an island
            default: op
          askyblock.mod.bypassprotect:
            description: Allow moderator to bypass island protection
            default: false
          askyblock.mod.setbiome:
            description: Allows setting player island biomes
            default: false
      askyblock.admin.*:
        children:
          askyblock.admin.reload:
            description: Reload the config.yml
            default: op
          askyblock.admin.delete:
            description: Let a player completely remove a player's island (including blocks)
            default: op
          askyblock.admin.register:
            description: Let a player register the nearest island (using the bedrock) to another player.
            default: op
          askyblock.admin.purge:
            description: Let a player purge old islands.
            default: op
          askyblock.admin.noburn:
            description: Gives admin immunity to acid
            default: false
          askyblock.admin.setspawn:
            description: Allows use of spawn tools
            default: op
