name: ASkyBlock
main: com.wasteofplastic.askyblock.ASkyBlock
version: ${version}
description: A SkyBlock Plugin
author: Tastybento
depend: [Vault]
softdepend: [Herochat]
load: startup
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Main player command
        aliases: [is, island]
        usage:  |
             /island help
    asadmin:
        description: Admin commands
        usage:  |
            /asadmin
    asc:
        description: Game challenges
        aliases: [c, challenge, aschallenge, challenges]
        usage:  |  
            /challenge
permissions:    
  askyblock.*:
    default: false
    children:
      askyblock.island.*:
        children:
          askyblock.island.go:
            description: Allow teleporting to player island
            default: true
          askyblock.island.create:
            description: Let the player use the /island command
            default: true
          askyblock.island.info:
            description: Let the player check their island level
            default: true
          askyblock.island.topten:
            description: Let the player see the top ten list
            default: true
          askyblock.island.sethome:
            description: Let the player set their island teleport point
            default: true
          askyblock.island.challenges:
            description: Let the player use the /challenges command
            default: true
          askyblock.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          askyblock.island.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
          askyblock.island.minishop:
            description: Allows usage of the minishop
            default: true
          askyblock.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
          askyblock.island.biomes:
            description: Allows biome changing
            default: true
          askyblock.island.lock:
            description: Allows island locking
            default: false
          askyblock.island.expel:
            description: Allows expelling of visitors
            default: true
          askyblock.island.ban:
            description: Allows banning of visitors
            default: false
          askyblock.island.settings:
            description: Player can see server settings
            default: true
          askyblock.island.lang:
            description: Player can select a language
            default: true
      askyblock.team.*:
        children:
          askyblock.team.create:
            description: Let a player invite other players to join a team
            default: true
          askyblock.team.kick:
            description: Let a player kick other players
            default: true
          askyblock.team.makeleader:
            description: Let a player make another player leader of the team
            default: true
          askyblock.team.join:
            description: Let a player join another player's team
            default: true
          askyblock.team.chat:
            description: Allow player to use team chat
            default: true
      askyblock.command.*:
        description: Event commands will not be run for players with this perm
        default: false
        children:
          askyblock.command.resetexempt:
            description: Player is exempt from commands run when island resets
            default: false
          askyblock.command.leaveexempt:
            description: Player is exempt from commands run when they leave or are kicked. Note will not help if player is offline.
            default: false
          askyblock.command.newexempt:
            description: Player is exempt from commands run when starting an island
            default: false
          askyblock.command.challengeexempt:
            description: Player is exempt from commands run when a challenge is completed
            default: false
      askyblock.coop:
        description: Allows player to use the coop command
        default: false    
      askyblock.craft.*:
        children:
          askyblock.craft.enderchest:
            description: Allow crafting and use of enderchests in askyblock
            default: false
          askyblock.craft.dirt:
            description: Allows tilling of coarse dirt into dirt
            default: false
      askyblock.excludetopten:
        description: Excludes player from top ten
        default: false
      askyblock.nohunger:
        description: Excludes player from hunger if on island
        default: false   
      askyblock.settings.*:
        children:
          askyblock.settings.allowAnvilUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowArmorStandUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBeaconAccess:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBedUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBreakBlocks:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBreeding:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBrewing:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowBucketUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowChestAccess:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowCrafting:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowCropTrample:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowDoorUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowEnchanting:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowEnderPearls:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowFurnaceUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowGateUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowHorseInvAccess:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowHorseRiding:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowHurtMobs:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowLeashUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowLeverButtonUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowMusic:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowPlaceBlocks:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowPortalUse:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowPressurePlate:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowPvP:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowNetherPvP:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowRedStone:
            description: Allow player to change this island guard setting
            default: false
          askyblock.settings.allowShearing:
            description: Allow player to change this island guard setting
            default: false
      askyblock.mod.*:
        children:
          askyblock.mod.topten:
            description: Let a moderator update the top ten list
            default: op
          askyblock.mod.info:
            description: Let a moderator see info on a player
            default: op
          askyblock.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          askyblock.mod.noburn:
            description: Gives mod immunity to acid
            default: false
          askyblock.mod.resethome:
            description: Allows setting or reseting of a player's home position
            default: op
          askyblock.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          askyblock.mod.tp:
            description: Allows teleport to an island
            default: op
          askyblock.mod.tpnether:
            description: Allows teleport to a nether island
            default: op
          askyblock.mod.bypassprotect:
            description: Allow moderator to bypass island protection
            default: op
          askyblock.mod.setbiome:
            description: Allows setting player island biomes
            default: op
          askyblock.mod.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          askyblock.mod.lock:
            description: Locks or unlocks an island
            default: op
          askyblock.mod.bypasslock:
            description: Bypasses an island lock
            default: op
          askyblock.mod.signadmin:
            description: Enables warp sign admin commands
            default: op
          askyblock.mod.spy:
            description: Spy on team chats
            default: false
          askyblock.mod.removesign:
            description: Gives ability to remove warp signs
            default: false
      askyblock.admin.*:
        children:
          askyblock.admin.clearresetall:
            description: Allow clearing of island reset limit of all players
            default: op
          askyblock.admin.reload:
            description: Reload the config.yml
            default: op
          askyblock.admin.delete:
            description: Let a player completely remove a player (including island)
            default: op
          askyblock.admin.deleteisland:
            description: Let a player completely remove the island the player is on
            default: op
          askyblock.admin.register:
            description: Let a player register the nearest island to another player.
            default: op
          askyblock.admin.unregister:
            description: Removes a player from an island without deleting the island blocks.
            default: op
          askyblock.admin.purge:
            description: Let a player purge old islands.
            default: op
          askyblock.admin.noburn:
            description: Gives admin immunity to acid
            default: false
          askyblock.admin.setspawn:
            description: Allows use of spawn tools
            default: op
          askyblock.admin.setrange:
            description: Allows setting of island protection range
            default: op
          askyblock.admin.topbreeders:
            description: Lists most populated islands current loaded
            default: op
